# NUMPY 

Nümerik ve hesaplamalı işlemler için geliştirilmiş bir kütüphanedir. 

**Neden Numpy ?**

Sabit tipte veri tuttuğu için daha hızlı işlem yapar ve verimli veri saklar. 

Vektörel işlemler yapma imkanı sağlar. 

Daha az çabayla daha fazla işlem gerçekleştirir.

In [ ]:
import numpy as np 

In [ ]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]
ab = []

for i in range(0, len(a)):
  ab.append(a[i] * b[i])
ab


[2, 6, 12, 20]

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
a*b

array([ 2,  6, 12, 20])

# Creating Numpy Arrays

In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
type(np.array([1, 2, 3, 4, 5]))

numpy.ndarray

In [ ]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.random.randint(0, 10, size = 12)  # (0 ile 10 arasındaki sayılardan 12 tane yazdır)

array([2, 7, 0, 7, 6, 1, 8, 2, 5, 2, 4, 0])

In [ ]:
# np.random.normal(ortalama, standart sapma, (matris satır, matris sütun))

np.random.normal(10, 4, (3, 4))   # ortalaması 10 ss 4 olan 3 e 4 lük rastgele değerli normal dağılımlı bir array oluşturdu

array([[ 4.79065828,  6.95974764, 17.21419752, 14.90154656],
       [10.34169022, 17.17053007,  7.42836007, 16.96219318],
       [11.8891819 , 16.19580818, 10.21889731,  6.17683579]])

# Attributes of NumPy Arrays 

ndim : boyut sayısı

shape : boyut bilgisi

size : toplam eleman sayısı

dtype : aarray veri tipi

In [ ]:
a = np.random.randint(10, size = 12)

In [ ]:
a.ndim

1

In [ ]:
a.shape 

(12,)

In [ ]:
a.size

12

In [ ]:
a.dtype

dtype('int64')

# Reshaping 

In [ ]:
np.random.randint(1, 10, size = 12)

array([1, 4, 1, 5, 6, 8, 3, 3, 8, 3, 6, 9])

In [ ]:
np.random.randint(1, 10, size = 12).reshape(3, 4)

array([[6, 1, 3, 8],
       [2, 6, 3, 8],
       [8, 6, 6, 5]])

# INDEX İşlemleri ***

## Index Selection

In [ ]:
a = np.random.randint(10, size = 12)

In [ ]:
a[0]

3

In [ ]:
a[0:5]

array([3, 8, 6, 8, 6])

In [ ]:
a[0] = 999
a

array([999,   8,   6,   8,   6,   6,   8,   2,   4,   3,   3,   4])

In [ ]:
m = np.random.randint(10, size = (3, 5))
m

array([[8, 9, 9, 0, 9],
       [4, 2, 4, 4, 2],
       [2, 1, 9, 5, 9]])

In [ ]:
m[0, 2] 

9

In [ ]:
m[1, 1]

2

In [ ]:
m[2, 3] = 99
m

array([[ 8,  9,  9,  0,  9],
       [ 4,  2,  4,  4,  2],
       [ 2,  1,  9, 99,  9]])

float bir değer girdin fakat integer bir değere dönüştürdü. NumPy der ki ben verimliyim bütün değerlerimi aynı özellikte tutarım.


In [ ]:
m[2, 3] = 8.5  
m

array([[8, 9, 9, 0, 9],
       [4, 2, 4, 4, 2],
       [2, 1, 9, 8, 9]])

In [ ]:
m[0:2, 0:1]

array([[8],
       [4]])

# Fancy Index

Birden fazla index bilgisini verir.

In [ ]:
v = np.arange(0, 30, 3) # 0 dan 30 a kadar 3 er 3 er artacak elemanlar
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
catch = [1, 2, 3]
v[catch]

array([3, 6, 9])

# Conditions on Numpy 

In [ ]:
v = np.array([1, 2, 3, 4, 5])

#klasik yolla liste içinden 3 ten küçük elemanları yakala
ab = []

for i in v:
  if i < 3:
    ab.append(i)

1
2


In [ ]:
v < 3

array([ True,  True, False, False, False])

In [ ]:
# Numpy ile

v[v < 3]

array([1, 2])

In [ ]:
print(v[v > 3])
print(v[v >= 3])
print(v[v <= 3])
print(v[v != 3])
print(v[v == 3])

[4 5]
[3 4 5]
[1 2 3]
[1 2 4 5]
[3]


# Mathematical Operations

In [ ]:
v = np.array([1, 2, 3, 4, 5])

print(v/5)
print(v*5/5)
print(v**5)
print(v-5)

[0.2 0.4 0.6 0.8 1. ]
[1. 2. 3. 4. 5.]
[   1   32  243 1024 3125]
[-4 -3 -2 -1  0]


In [ ]:
print(np.subtract(v, 1))  # çıkarma
print(np.add(v, 1)) # toplama
print(np.mean(v)) # ortalama
print(np.sum(v)) # liste içindeki bütün elemanların toplamı
print(np.min(v)) # listedeki en küçük eleman
print(np.max(v)) # listedeki en büyük eleman
print(np.var(v)) # varyasyonu

[0 1 2 3 4]
[2 3 4 5 6]
3.0
15
1
5
2.0


In [ ]:
 #iki bilinmeyenli denklemin çözümü
 # 5*x0 + x1 = 12
 # x0 + 3*x1 = 10

a =np.array([[5, 1], [1, 3]])
b= np.array([12, 10])

np.linalg.solve(a, b)

array([1.85714286, 2.71428571])

#PANDAS 

Veri işlemesi ve analizi için Python programlama dilinde yazılmış olan bir yazılım kütüphanesidir

###PANDAS SERIES

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10, 77, 12, 4, 5])
type(s)

pandas.core.series.Series

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.size

5

In [ ]:
s.ndim  #pandas serileri tek boyutludur

1

In [ ]:
s.values # indexle ilgilenmiyorum dediğin için numpy array olarak döndürür

array([10, 77, 12,  4,  5])

In [ ]:
type(s.values) 

numpy.ndarray

In [ ]:
s.head(2)

0    10
1    77
dtype: int64

In [ ]:
s.tail(3)

2    12
3     4
4     5
dtype: int64

In [ ]:
s.head()

0    10
1    77
2    12
3     4
4     5
dtype: int64

# READING DATA

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [ ]:
import pandas as pd
import seaborn as sns
adv = pd.read_csv('/content/gdrive/My Drive/advertising.csv')
df = adv.copy()
df.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

# Quick Look at Data

In [ ]:
df = sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [ ]:
df.describe().T

count       mean        std   min      25%      50%   75%       max
survived  891.0   0.383838   0.486592  0.00   0.0000   0.0000   1.0    1.0000
pclass    891.0   2.308642   0.836071  1.00   2.0000   3.0000   3.0    3.0000
age       714.0  29.699118  14.526497  0.42  20.1250  28.0000  38.0   80.0000
sibsp     891.0   0.523008   1.102743  0.00   0.0000   0.0000   1.0    8.0000
parch     891.0   0.381594   0.806057  0.00   0.0000   0.0000   0.0    6.0000
fare      891.0  32.204208  49.693429  0.00   7.9104  14.4542  31.0  512.3292

In [ ]:
df.isnull().values

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [ ]:
df.isnull().values.any() #en az bir tane eksik değer var mı ?

True

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df["sex"].head()

0      male
1    female
2    female
3    female
4      male
Name: sex, dtype: object

In [ ]:
df["sex"].value_counts()

male      577
female    314
Name: sex, dtype: int64

#Selection in Pandas

In [ ]:
df[0:10]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [ ]:
df.drop(0, axis = 0).head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   

     who  adult_male deck  embark_town alive  alone  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True

In [ ]:
delete_indexes = [1, 3, 5, 7]
df.drop(delete_indexes, axis = 0).head() # bu silme işlemi kalıcı değildir.

#kalıcı olması için df e tekrar atama yapabilirsin. 
# df = df.drop(delete_indexes, axis = 0).head() şeklinde olur. Ya da
# df.drop(delete_indexes, axis = 0, inplace = True).head() # inplace = True eklersin.

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
2         1       3  female  26.0      0      0   7.9250        S  Third   
4         0       3    male  35.0      0      0   8.0500        S  Third   
6         0       1    male  54.0      0      0  51.8625        S  First   
8         1       3  female  27.0      0      2  11.1333        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
2  woman       False  NaN  Southampton   yes   True  
4    man        True  NaN  Southampton    no   True  
6    man        True    E  Southampton    no   True  
8  woman       False  NaN  Southampton   yes  False

# **Önemli :** Değişkeni Index'e çevirme

In [ ]:
#df["age"].head()
df.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [ ]:
df.index = df["age"]   #yaş bilgisi indexe eklendi
df.index

Float64Index([22.0, 38.0, 26.0, 35.0, 35.0,  nan, 54.0,  2.0, 27.0, 14.0,
              ...
              33.0, 22.0, 28.0, 25.0, 39.0, 27.0, 19.0,  nan, 26.0, 32.0],
             dtype='float64', name='age', length=891)

In [ ]:
df.drop("age", axis = 1).head()

survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
age                                                                            
22.0         0       3    male      1      0   7.2500        S  Third    man   
38.0         1       1  female      1      0  71.2833        C  First  woman   
26.0         1       3  female      0      0   7.9250        S  Third  woman   
35.0         1       1  female      1      0  53.1000        S  First  woman   
35.0         0       3    male      0      0   8.0500        S  Third    man   

      adult_male deck  embark_town alive  alone  
age                                              
22.0        True  NaN  Southampton    no  False  
38.0       False    C    Cherbourg   yes  False  
26.0       False  NaN  Southampton   yes   True  
35.0       False    C  Southampton   yes  False  
35.0        True  NaN  Southampton    no   True

In [ ]:
df.drop("age", axis = 1, inplace = True)
df.head()

survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
age                                                                            
22.0         0       3    male      1      0   7.2500        S  Third    man   
38.0         1       1  female      1      0  71.2833        C  First  woman   
26.0         1       3  female      0      0   7.9250        S  Third  woman   
35.0         1       1  female      1      0  53.1000        S  First  woman   
35.0         0       3    male      0      0   8.0500        S  Third    man   

      adult_male deck  embark_town alive  alone  
age                                              
22.0        True  NaN  Southampton    no  False  
38.0       False    C    Cherbourg   yes  False  
26.0       False  NaN  Southampton   yes   True  
35.0       False    C  Southampton   yes  False  
35.0        True  NaN  Southampton    no   True

In [ ]:
df["age"] = df.index #indexteki değer kolona eklendi

In [ ]:
df.head()

survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
age                                                                            
22.0         0       3    male      1      0   7.2500        S  Third    man   
38.0         1       1  female      1      0  71.2833        C  First  woman   
26.0         1       3  female      0      0   7.9250        S  Third  woman   
35.0         1       1  female      1      0  53.1000        S  First  woman   
35.0         0       3    male      0      0   8.0500        S  Third    man   

      adult_male deck  embark_town alive  alone   age  
age                                                    
22.0        True  NaN  Southampton    no  False  22.0  
38.0       False    C    Cherbourg   yes  False  38.0  
26.0       False  NaN  Southampton   yes   True  26.0  
35.0       False    C  Southampton   yes  False  35.0  
35.0        True  NaN  Southampton    no   True  35.0

In [ ]:
# ikinci yol 
df.drop("age", axis = 1, inplace = True)
df = df.reset_index().head()

In [ ]:
df.head()

age  survived  pclass     sex  sibsp  parch     fare embarked  class  \
0  22.0         0       3    male      1      0   7.2500        S  Third   
1  38.0         1       1  female      1      0  71.2833        C  First   
2  26.0         1       3  female      0      0   7.9250        S  Third   
3  35.0         1       1  female      1      0  53.1000        S  First   
4  35.0         0       3    male      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

#Değişkenler Üzerinden İşlemler

In [ ]:
# çok fazla kolon olduğu zaman ara kolonlarıda görmek için eklemen gereken kod:
# pd.set_option("display.max_columns", None)

In [ ]:
type(df["age"].head())  

pandas.core.series.Series

In [ ]:
 #değişken seçerken o değişkenin dataframe olarak kalmasını istiyorsan iki köşeli parantez kullanmalısın.
 df[["age"]].head()

age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0

In [ ]:
type( df[["age"]].head())

pandas.core.frame.DataFrame

In [ ]:
# ikiden fazla değişken seçme

df[["age", "alive", "alone"]]

age alive  alone
0  22.0    no  False
1  38.0   yes  False
2  26.0   yes   True
3  35.0   yes  False
4  35.0    no   True

In [ ]:
# yeni değişken ekleme

df["age2"] = df["age"]**2
df.head()

age  survived  pclass     sex  sibsp  parch     fare embarked  class  \
0  22.0         0       3    male      1      0   7.2500        S  Third   
1  38.0         1       1  female      1      0  71.2833        C  First   
2  26.0         1       3  female      0      0   7.9250        S  Third   
3  35.0         1       1  female      1      0  53.1000        S  First   
4  35.0         0       3    male      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone    age2  
0    man        True  NaN  Southampton    no  False   484.0  
1  woman       False    C    Cherbourg   yes  False  1444.0  
2  woman       False  NaN  Southampton   yes   True   676.0  
3  woman       False    C  Southampton   yes  False  1225.0  
4    man        True  NaN  Southampton    no   True  1225.0

In [ ]:
df.drop("age2", axis = 1, inplace=True)

In [ ]:
df.head()

age  survived  pclass     sex  sibsp  parch     fare embarked  class  \
0  22.0         0       3    male      1      0   7.2500        S  Third   
1  38.0         1       1  female      1      0  71.2833        C  First   
2  26.0         1       3  female      0      0   7.9250        S  Third   
3  35.0         1       1  female      1      0  53.1000        S  First   
4  35.0         0       3    male      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
# birden fazla değişken silmek istiyorsan ayrı bir liste tanımla ve "age2" nin olduğu yere yeni tanımladığın listenin ismini yaz.

# mesela del_columns = ["age", "alone", "fare"]
# df.drop(del_columns, axis = 1, inplace=True)

LOC & ILOC 

loc : label based selection

iloc: integer based selection

DataFrame lerde seçim işlemi yapmak için kullanılır.

In [ ]:
a = df.loc[:, df.columns.str.contains("age")]
a.head()

age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0

In [ ]:
# tilda "~" işareti bunun dışındakileri seç demek yani age dışındakileri seçtik
b = df.loc[:, ~df.columns.str.contains("age")]
b

survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
0         0       3    male      1      0   7.2500        S  Third    man   
1         1       1  female      1      0  71.2833        C  First  woman   
2         1       3  female      0      0   7.9250        S  Third  woman   
3         1       1  female      1      0  53.1000        S  First  woman   
4         0       3    male      0      0   8.0500        S  Third    man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
1       False    C    Cherbourg   yes  False  
2       False  NaN  Southampton   yes   True  
3       False    C  Southampton   yes  False  
4        True  NaN  Southampton    no   True

In [ ]:
df.iloc[0:3] # 0'dan 3'e kadar seçti

age  survived  pclass     sex  sibsp  parch     fare embarked  class  \
0  22.0         0       3    male      1      0   7.2500        S  Third   
1  38.0         1       1  female      1      0  71.2833        C  First   
2  26.0         1       3  female      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

In [ ]:
df.loc[0:3] # 0'dan başlayıp 3 de seçti

age  survived  pclass     sex  sibsp  parch     fare embarked  class  \
0  22.0         0       3    male      1      0   7.2500        S  Third   
1  38.0         1       1  female      1      0  71.2833        C  First   
2  26.0         1       3  female      0      0   7.9250        S  Third   
3  35.0         1       1  female      1      0  53.1000        S  First   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False

In [ ]:
df.iloc[0:3, 0:3]

age  survived  pclass
0  22.0         0       3
1  38.0         1       1
2  26.0         1       3

In [ ]:
df.loc[0:3, "age"]

0    22.0
1    38.0
2    26.0
3    35.0
Name: age, dtype: float64

In [ ]:
col_names = ["age", "embarked", "alive"]
df.loc[0:3, col_names]

age embarked alive
0  22.0        S    no
1  38.0        C   yes
2  26.0        S   yes
3  35.0        S   yes

# CONDITIONAL SELECTION

In [ ]:
df.head()

age  survived  pclass     sex  sibsp  parch     fare embarked  class  \
0  22.0         0       3    male      1      0   7.2500        S  Third   
1  38.0         1       1  female      1      0  71.2833        C  First   
2  26.0         1       3  female      0      0   7.9250        S  Third   
3  35.0         1       1  female      1      0  53.1000        S  First   
4  35.0         0       3    male      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
df[df["age"] > 50]
df[df["age"] > 20].count()

age            5
survived       5
pclass         5
sex            5
sibsp          5
parch          5
fare           5
embarked       5
class          5
who            5
adult_male     5
deck           2
embark_town    5
alive          5
alone          5
dtype: int64

In [ ]:
df[df["age"] > 20]["age"].count()

5

In [ ]:
df.loc[df["age"] > 20, ["age", "class"]].head()

age  class
0  22.0  Third
1  38.0  First
2  26.0  Third
3  35.0  First
4  35.0  Third

In [ ]:
# birden fazla koşul gireceksen parantez içine al 

df.loc[(df["age"] > 20) & (df["sex"] == "male"), ["age", "class"]].head()

age  class
0  22.0  Third
4  35.0  Third

In [ ]:
df["embark_town"].value_counts()

Southampton    644
Cherbourg      168
Queenstown      77
Name: embark_town, dtype: int64

In [ ]:
df_new = df.loc[(df["age"] > 50) & 
       (df["sex"] == "male")  & 
       ((df["embark_town"] == "Cherbourg") | (df["embark_town"] == "Southampton")), 
        ["age", "class","embark_town"]]
df_new

age   class  embark_town
6    54.0   First  Southampton
33   66.0  Second  Southampton
54   65.0   First    Cherbourg
94   59.0   Third  Southampton
96   71.0   First    Cherbourg
124  54.0   First  Southampton
150  51.0  Second  Southampton
152  55.5   Third  Southampton
155  51.0   First    Cherbourg
170  61.0   First  Southampton
174  56.0   First    Cherbourg
222  51.0   Third  Southampton
232  59.0  Second  Southampton
249  54.0  Second  Southampton
252  62.0   First  Southampton
262  52.0   First  Southampton
317  54.0  Second  Southampton
326  61.0   Third  Southampton
406  51.0   Third  Southampton
438  64.0   First  Southampton
449  52.0   First  Southampton
456  65.0   First  Southampton
467  56.0   First  Southampton
487  58.0   First    Cherbourg
492  55.0   First  Southampton
493  71.0   First    Cherbourg
545  64.0   First  Southampton
555  62.0   First  Southampton
570  62.0  Second  Southampton
582  54.0  Second  Southampton
587  60.0   First    Cherbourg
625  61.0   First  Southampton
630  80.0   First  Southampton
631  51.0   Third  Southampton
647  56.0   First    Cherbourg
659  58.0   First    Cherbourg
672  70.0  Second  Southampton
684  60.0  Second  Southampton
694  60.0   First  Southampton
695  52.0  Second  Southampton
714  52.0  Second  Southampton
745  70.0   First  Southampton
851  74.0   Third  Southampton
857  51.0   First  Southampton

In [ ]:
df_new["embark_town"].value_counts()

Southampton    35
Cherbourg       9
Name: embark_town, dtype: int64

#  Aggregation & Grouping

In [ ]:
df["age"].mean()

29.69911764705882

In [ ]:
df.groupby("sex")["age"].mean()

sex
female    27.915709
male      30.726645
Name: age, dtype: float64

In [ ]:
df.groupby("sex").agg({"age": "mean"}) #dictionary formatını daha sık kullanırsın öğren !

age
sex              
female  27.915709
male    30.726645

In [ ]:
df.groupby("sex").agg({"age": ["mean", "sum"]})

age          
             mean       sum
sex                        
female  27.915709   7286.00
male    30.726645  13919.17

In [ ]:
df.groupby("sex").agg({"age": ["mean", "sum"],
                       "embark_town": "count",
                       "survived": "mean"})

age           embark_town  survived
             mean       sum       count      mean
sex                                              
female  27.915709   7286.00         312  0.742038
male    30.726645  13919.17         577  0.188908

In [ ]:
df.groupby(["sex", "embark_town"]).agg({"age": "mean", "survived": "mean"})

age  survived
sex    embark_town                     
female Cherbourg    28.344262  0.876712
       Queenstown   24.291667  0.750000
       Southampton  27.771505  0.689655
male   Cherbourg    32.998841  0.305263
       Queenstown   30.937500  0.073171
       Southampton  30.291440  0.174603

In [ ]:
df.groupby(["sex", "embark_town", "class"]).agg({"age": "mean",
                                                 "survived": "mean", 
                                                 "sex": "count"})

age  survived  sex
sex    embark_town class                           
female Cherbourg   First   36.052632  0.976744   43
                   Second  19.142857  1.000000    7
                   Third   14.062500  0.652174   23
       Queenstown  First   33.000000  1.000000    1
                   Second  30.000000  1.000000    2
                   Third   22.850000  0.727273   33
       Southampton First   32.704545  0.958333   48
                   Second  29.719697  0.910448   67
                   Third   23.223684  0.375000   88
male   Cherbourg   First   40.111111  0.404762   42
                   Second  25.937500  0.200000   10
                   Third   25.016800  0.232558   43
       Queenstown  First   44.000000  0.000000    1
                   Second  57.000000  0.000000    1
                   Third   28.142857  0.076923   39
       Southampton First   41.897188  0.354430   79
                   Second  30.875889  0.154639   97
                   Third   26.574766  0.128302  265

# PIVOT TABLE

df.pivot_table("ilk değişkenin ortalaması, "satır değeri", "sütun değeri")

In [ ]:
df.pivot_table("survived", "sex", "embarked")

embarked         C         Q         S
sex                                   
female    0.876712  0.750000  0.689655
male      0.305263  0.073171  0.174603

In [ ]:
df.pivot_table("survived", "sex", "embarked", aggfunc = "std")

embarked         C         Q         S
sex                                   
female    0.331042  0.439155  0.463778
male      0.462962  0.263652  0.380058

In [ ]:
df.pivot_table("survived", "sex", ["embarked","class"])

embarked         C                      Q                          S  \
class        First Second     Third First Second     Third     First   
sex                                                                    
female    0.976744    1.0  0.652174   1.0    1.0  0.727273  0.958333   
male      0.404762    0.2  0.232558   0.0    0.0  0.076923  0.354430   

embarked                      
class       Second     Third  
sex                           
female    0.910448  0.375000  
male      0.154639  0.128302

In [ ]:
df = sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
df["new_age"] = pd.cut(df["age"], [0, 10, 18, 25, 40, 90])
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone   new_age  
0    man        True  NaN  Southampton    no  False  (18, 25]  
1  woman       False    C    Cherbourg   yes  False  (25, 40]  
2  woman       False  NaN  Southampton   yes   True  (25, 40]  
3  woman       False    C  Southampton   yes  False  (25, 40]  
4    man        True  NaN  Southampton    no   True  (25, 40]

In [ ]:
df.pivot_table("survived", "sex", ["new_age", "class"])

new_age (0, 10]                   (10, 18]                   (18, 25]  \
class     First Second     Third     First Second     Third     First   
sex                                                                     
female      0.0    1.0  0.500000  1.000000    1.0  0.523810  0.941176   
male        1.0    1.0  0.363636  0.666667    0.0  0.103448  0.333333   

new_age                      (25, 40]                      (40, 90]            \
class      Second     Third     First    Second     Third     First    Second   
sex                                                                             
female   0.933333  0.500000  1.000000  0.906250  0.464286  0.961538  0.846154   
male     0.047619  0.115385  0.513514  0.071429  0.172043  0.280000  0.095238   

new_age            
class       Third  
sex                
female   0.111111  
male     0.064516

# APPLY & LAMBDA

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df = sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
df["age2"] = df["age"]*2
df["age3"] = df["age"]*5

In [ ]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age2   age3  
0    man        True  NaN  Southampton    no  False  44.0  110.0  
1  woman       False    C    Cherbourg   yes  False  76.0  190.0  
2  woman       False  NaN  Southampton   yes   True  52.0  130.0  
3  woman       False    C  Southampton   yes  False  70.0  175.0  
4    man        True  NaN  Southampton    no   True  70.0  175.0

In [ ]:
(df["age"]/10).head()

0    2.2
1    3.8
2    2.6
3    3.5
4    3.5
Name: age, dtype: float64

In [ ]:
for col in df.columns:
  if "age" in col:
    print(col)

age
age2
age3


In [ ]:
#içinde age değişkeni olan bütün kolonları 10'a böl bu kod geçici olarak atadı
for col in df.columns:
  if "age" in col:
    print((df[col]/10).head())

0    2.2
1    3.8
2    2.6
3    3.5
4    3.5
Name: age, dtype: float64
0    4.4
1    7.6
2    5.2
3    7.0
4    7.0
Name: age2, dtype: float64
0    11.0
1    19.0
2    13.0
3    17.5
4    17.5
Name: age3, dtype: float64


In [ ]:
# kalıcı olarak atamak için

for col in df.columns:
  if "age" in col:
    df[col] = df[col]/10
df.head()

survived  pclass     sex  age  sibsp  parch     fare embarked  class  \
0         0       3    male  2.2      1      0   7.2500        S  Third   
1         1       1  female  3.8      1      0  71.2833        C  First   
2         1       3  female  2.6      0      0   7.9250        S  Third   
3         1       1  female  3.5      1      0  53.1000        S  First   
4         0       3    male  3.5      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age2  age3  
0    man        True  NaN  Southampton    no  False   4.4  11.0  
1  woman       False    C    Cherbourg   yes  False   7.6  19.0  
2  woman       False  NaN  Southampton   yes   True   5.2  13.0  
3  woman       False    C  Southampton   yes  False   7.0  17.5  
4    man        True  NaN  Southampton    no   True   7.0  17.5

In [ ]:
df[["age", "age2", "age3"]].apply(lambda x: x/10).head()

age  age2  age3
0  0.22  0.44  1.10
1  0.38  0.76  1.90
2  0.26  0.52  1.30
3  0.35  0.70  1.75
4  0.35  0.70  1.75

In [ ]:
#2.yol apply lambda ile döngü yazmadan değişkenler üzerinde gezme işlemi sağladı
df.loc[:, df.columns.str.contains("age")].apply(lambda x: x/10).head()

age  age2  age3
0  0.22  0.44  1.10
1  0.38  0.76  1.90
2  0.26  0.52  1.30
3  0.35  0.70  1.75
4  0.35  0.70  1.75

In [ ]:
df.loc[:, df.columns.str.contains("age")].apply(lambda x: (x-x.mean())/ x.std()).head()

age      age2      age3
0 -0.530005 -0.530005 -0.530005
1  0.571430  0.571430  0.571430
2 -0.254646 -0.254646 -0.254646
3  0.364911  0.364911  0.364911
4  0.364911  0.364911  0.364911

In [ ]:
def standart_scaler(col_name):
  return(col_name - col_name.mean()) / col_name.std()
df.loc[:, df.columns.str.contains("age")].apply(standart_scaler).head()

age      age2      age3
0 -0.530005 -0.530005 -0.530005
1  0.571430  0.571430  0.571430
2 -0.254646 -0.254646 -0.254646
3  0.364911  0.364911  0.364911
4  0.364911  0.364911  0.364911

In [ ]:
#kaydetmek için 1.yol:
df.loc[:, ["age", "age2", "age3"]] = df.loc[:, df.columns.str.contains("age")].apply(standart_scaler).head()

In [ ]:
#kaydetmek için 2.yol:
df.loc[:, df.columns.str.contains("age")] = df.loc[:, df.columns.str.contains("age")].apply(standart_scaler).head()

In [ ]:
df.head()

survived  pclass     sex       age  sibsp  parch     fare embarked  class  \
0         0       3    male -1.346261      1      0   7.2500        S  Third   
1         1       1  female  0.995063      1      0  71.2833        C  First   
2         1       3  female -0.760930      0      0   7.9250        S  Third   
3         1       1  female  0.556064      1      0  53.1000        S  First   
4         0       3    male  0.556064      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone      age2      age3  
0    man        True  NaN  Southampton    no  False -1.346261 -1.346261  
1  woman       False    C    Cherbourg   yes  False  0.995063  0.995063  
2  woman       False  NaN  Southampton   yes   True -0.760930 -0.760930  
3  woman       False    C  Southampton   yes  False  0.556064  0.556064  
4    man        True  NaN  Southampton    no   True  0.556064  0.556064

# BİRLEŞTİRME (JOIN) İŞLEMLERİ

In [ ]:
import pandas as pd
import numpy as np

m = np.random.randint(1, 30, size = (5, 3))

df1 = pd.DataFrame(m, columns=["var1", "var2", "var3"])

df2 = df1 + 99
print(m)
print(df1)
print(df2)

[[15 10  1]
 [14  5 12]
 [23  6 25]
 [ 5  6 24]
 [27 13 12]]
   var1  var2  var3
0    15    10     1
1    14     5    12
2    23     6    25
3     5     6    24
4    27    13    12
   var1  var2  var3
0   114   109   100
1   113   104   111
2   122   105   124
3   104   105   123
4   126   112   111


In [ ]:
pd.concat([df1, df2]) 

var1  var2  var3
0    15    10     1
1    14     5    12
2    23     6    25
3     5     6    24
4    27    13    12
0   114   109   100
1   113   104   111
2   122   105   124
3   104   105   123
4   126   112   111

**ignore_index = True** : Birleştirilen 2.dataframe index 'i 0 dan başlatır. Bunu yok etmek için kullanılır

In [ ]:
pd.concat([df1, df2], ignore_index = True) 

var1  var2  var3
0    15    10     1
1    14     5    12
2    23     6    25
3     5     6    24
4    27    13    12
5   114   109   100
6   113   104   111
7   122   105   124
8   104   105   123
9   126   112   111

In [ ]:
# example

df1 = pd.DataFrame({"employees": ["John", "Dennis", "Mark", "Maria"],
                    "group": ["accounting", "engineering", "engineering", "hr"]})


df2 = pd.DataFrame({"employees": ["John", "Dennis", "Mark", "Maria"],
                    "start_date": [2010, 2009, 2014, 2019]})
print(df1)
print(df2)

  employees        group
0      John   accounting
1    Dennis  engineering
2      Mark  engineering
3     Maria           hr
  employees  start_date
0      John        2010
1    Dennis        2009
2      Mark        2014
3     Maria        2019


In [ ]:
pd.merge(df1, df2) #belirtmeden employees e göre birleştirdi. 

employees        group  start_date
0      John   accounting        2010
1    Dennis  engineering        2009
2      Mark  engineering        2014
3     Maria           hr        2019

In [ ]:
#belirtmek istersende aşağıdaki gibi yapabilirsin.

pd.merge(df1, df2, on = "employees")

employees        group  start_date
0      John   accounting        2010
1    Dennis  engineering        2009
2      Mark  engineering        2014
3     Maria           hr        2019

In [ ]:
# AMAÇ: Her çalışanın müdürünün bilgisine erişmek istiyoruz.

df3 = pd.merge(df1, df2)

df4 = pd.DataFrame({"group": ["accounting", "engineering", "hr"],
        "manager": ["Caner", "Mustafa", "Berkcan"]})
print(df4)


         group  manager
0   accounting    Caner
1  engineering  Mustafa
2           hr  Berkcan


In [ ]:
pd.merge(df3, df4, on = "group")

employees        group  start_date  manager
0      John   accounting        2010    Caner
1    Dennis  engineering        2009  Mustafa
2      Mark  engineering        2014  Mustafa
3     Maria           hr        2019  Berkcan